### ISSUE TITLE
quick_start does not work

### ISSUE THREAD

**Issue by Stevenhunter167** [dojo-sim/dojopy#5]
python3 quick_start.py 
Traceback (most recent call last):
  File "quick_start.py", line 6, in <module>
    env = dojo.get_environment('pendulum')
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/julia/core.py", line 176, in __getattr__
    return self.__try_getattr(name)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/julia/core.py", line 199, in __try_getattr
    raise AttributeError(name)
AttributeError: get_environment

I followed installation using docker and got above error when running quick_start.py

**Comment by buzi-princeton** [comment]
I have the same problem with @Stevenhunter167, has anyone been able to address this issue?

**Comment by buzi-princeton** [comment]
> I have the same problem with @Stevenhunter167, has anyone been able to address this issue?

Fix this by replacing the final line of Dockerfile with:

`RUN julia -e 'ENV["JULIA_SSL_NO_VERIFY_HOSTS"] = "julialang.org"; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); try; Pkg.add("Dojo"); catch LoadError; end; try; Pkg.add("Dojo"); catch LoadError; end; try; Pkg.add("DojoEnvironments"); catch LoadError; end'`

Then in `quick_start.py` file, use:
`DojoEnvironments.get_environment('pendulum')`
